# Generated by Django 3.2.7 on 2021-09-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptopname', models.CharField(max_length=40)),
                ('laptopcompany', models.CharField(max_length=50)),
                ('laptopram', models.CharField(max_length=30)),
                ('laptoprom', models.CharField(max_length=30)),
                ('laptopprice', models.CharField(max_length=30)),
                ('laptopprocessor', models.CharField(max_length=40)),
            ],
        ),
    ]
